### ISSUE TITLE
Consider using keen proxy 

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/email-analytics-service#118]
Re: https://github.com/Financial-Times/keen-proxy/issues/3

> Essentially, just change https://api.keen.io/* to https://keen-proxy.ft.com/*

Keen proxy tends to speed up responses and reduces load on keen.io, so it's worth considering. https://github.com/Financial-Times/keen-proxy

**Comment by syymza** [comment]
We currently use the `max-age` queryString param, which allow us to achieve the same thing easily
